spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/Pessoa
    platform: postgres
    password: vicente0301
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
server:
  port: '8082'
